name: pi_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  awesome_flutter_extensions: ^1.2.0
  go_router: ^14.2.7
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.2
  loggy: ^2.0.3
  slang: ^3.31.2
  slang_flutter: ^3.31.0
  dio: ^5.7.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  path_provider: ^2.1.4
  flutter_foreground_task: ^8.10.0
  uuid: ^4.5.1
  intl: ^0.19.0
  fl_location: ^4.1.0+1
  latlong2: ^0.9.1
  collection: ^1.18.0
  fl_chart: ^0.69.0
  package_info_plus: ^8.0.3
  hive: ^2.2.3
  isar:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  fpdart: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  go_router_builder: any
  build_runner: ^2.4.11
  build_verify: any
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  slang_build_runner: ^3.31.0
  isar_generator:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/

flutter:
  uses-material-design: true
  assets:
    - assets/
