name: pi_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  awesome_flutter_extensions: ^1.2.0
  go_router: ^14.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  go_router_builder: any
  build_runner: any
  build_verify: any

flutter:
  uses-material-design: true
  assets:
    - assets/
